### ISSUE TITLE
adding new slice type

### ISSUE THREAD

**Issue by mhmd97z** [jjalcaraz-upct/network-slicing#3]
Hi!

I want to add a new slice type to the simulator and solve the RAN slicing problem using KBRL. To do so, I think I just need to add a description of the new type to scenario_creator.py and the new _for_ loop (like [this](https://github.com/jjalcaraz-upct/network-slicing/blob/fef706d7937af6a1dd0cee73c2aa39f266dd2ae8/scenario_creator.py#L216)) in the same file to add the corresponding learners. 

Are there any other modifications I need to do?

**Comment by jjalcaraz-upct** [comment]
Hello Mohammad,

Yes, in that for loop is where you define a learner for each network slice by specifying, among other things, which elements of the system observation array are provided to each learner (this is the “slice” provided as second argument to Learner, which is a python slice, not to confuse with the simulated RAN slice).

Adding a new RAN slice type different from mMTC and eMBB (e.g. URLLC) would require of course modifications in other files (new classes in slice_l1.py, slice_ran.py, possibly new traffic sources in traffic_generators.py…), but not to the KBRL algorithm.

BR,

Juanjo


From: Mohammad Zangooei ***@***.***>
Reply-To: jjalcaraz-upct/network-slicing ***@***.***>
Date: Wednesday, December 14, 2022 at 3:17 PM
To: jjalcaraz-upct/network-slicing ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jjalcaraz-upct/network-slicing] adding new slice type (Issue #3)


Hi!

I want to add a new slice type to the simulator and solve the RAN slicing problem using KBRL. To do so, I think I just need to add a description of the new type to scenario_creator.py and the new for loop (like this<https://github.com/jjalcaraz-upct/network-slicing/blob/fef706d7937af6a1dd0cee73c2aa39f266dd2ae8/scenario_creator.py#L216>) in the same file to add the corresponding learners.

Are there any other modifications I need to do?

**Comment by mhmd97z** [comment]
Thanks for the prompt response.
